services:
  fcp-mpdp-backend:
    build:
      target: development
    image: fcp-mpdp-backend-development
    container_name: fcp-mpdp-backend-test
    command: npm test
    volumes:
      - ./src:/home/node/src
      - ./test:/home/node/test
      - ./package.json:/home/node/package.json