services:
  fcp-mpdp-backend:
    build:
      target: development
    image: fcp-mpdp-backend-development
    command: npm test
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_started
    volumes:
      - ./test:/home/node/test
      - ./coverage:/home/node/coverage
