services:
  fcp-mpdp-backend:
    build:
      context: .
      target: development
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_HOST_READ: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_GET_TOKEN_FROM_RDS: false
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  postgres:
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fcp_mpdp_backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 10s

  liquibase:
    image: liquibase/liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./changelog:/liquibase/changelog
    command: --url=jdbc:postgresql://postgres:5432/fcp_mpdp_backend --username=postgres --password=postgres --changelog-file=changelog/db.changelog.xml update
